-- 149_grammar_en_es_de_fr.sql
-- Грамматика для en/es/de/fr (conjugation/article/past/futuro). Итальянский НЕ трогаем.
-- Идемпотентно: CHECK + полная переустановка строк этих 4 языков.
ALTER TABLE public.grammar_items DROP CONSTRAINT IF EXISTS grammar_items_language_check;
ALTER TABLE public.grammar_items ADD  CONSTRAINT grammar_items_language_check CHECK (language IN ('en','it','es','de','fr'));
DELETE FROM public.grammar_items WHERE language IN ('en','es','de','fr');

INSERT INTO public.grammar_items (language, kind, level, topic, order_index, prompt, prompt_ru, answer, options, explain_ru) VALUES
('en','conjugation','A1','present',1,'I ___ a student.','Я студент(ка).','am','["am", "is", "are"]','to be: I am, you/we/they are, he/she/it is'),
('en','conjugation','A1','present',2,'She ___ happy.','Она счастлива.','is','["am", "is", "are"]','to be: I am, you/we/they are, he/she/it is'),
('en','conjugation','A1','present',3,'They ___ friends.','Они друзья.','are','["am", "is", "are"]','to be: I am, you/we/they are, he/she/it is'),
('en','conjugation','A1','present',4,'You ___ right.','Ты прав.','are','["am", "is", "are"]','to be: I am, you/we/they are, he/she/it is'),
('en','conjugation','A1','present',5,'He ___ a car.','У него есть машина.','has','["have", "has", "haves"]','to have: I/you/we/they have, he/she/it has'),
('en','conjugation','A1','present',6,'We ___ time.','У нас есть время.','have','["have", "has", "having"]','to have: I/you/we/they have, he/she/it has'),
('en','conjugation','A1','present',7,'She ___ English.','Она говорит по-английски.','speaks','["speak", "speaks", "speakes"]','3-е лицо ед.ч.: глагол + -s/-es'),
('en','conjugation','A1','present',8,'He ___ to work.','Он ходит на работу.','goes','["go", "goes", "gos"]','go → goes'),
('en','conjugation','A1','present',9,'I ___ coffee.','Я люблю кофе.','like','["like", "likes", "liking"]','I/you/we/they — без -s'),
('en','past','A2','past',10,'Yesterday I ___ to school.','Вчера я пошёл в школу.','went','["went", "goed", "go"]','go → went (неправильный)'),
('en','past','A2','past',11,'She ___ a book.','Она прочитала книгу.','read','["read", "readed", "reads"]','read → read (форма не меняется в написании)'),
('en','past','A2','past',12,'They ___ happy.','Они были счастливы.','were','["was", "were", "are"]','was: I/he/she/it; were: you/we/they'),
('en','past','A2','past',13,'He ___ at home.','Он был дома.','was','["was", "were", "is"]','was: I/he/she/it'),
('en','past','A2','past',14,'We ___ pizza.','Мы ели пиццу.','ate','["ate", "eated", "eat"]','eat → ate'),
('en','past','A2','past',15,'I ___ a car.','У меня была машина.','had','["had", "haved", "has"]','have → had'),
('en','past','A2','past',16,'She ___ to me.','Она говорила со мной.','spoke','["spoke", "speaked", "speak"]','speak → spoke'),
('en','past','A2','past',17,'They ___ the film.','Они посмотрели фильм.','saw','["saw", "seed", "see"]','see → saw'),
('en','futuro','A2','future',18,'Tomorrow I ___ help you.','Завтра я помогу тебе.','will','["will", "was", "am"]','will + глагол — будущее'),
('en','futuro','A2','future',19,'It ___ rain later.','Позже пойдёт дождь.','will','["will", "is", "does"]','will + глагол'),
('en','futuro','A2','future',20,'They ___ arrive soon.','Они скоро приедут.','will','["will", "were", "are"]','will + глагол'),
('en','article','A1','articles',21,'I have ___ apple.','У меня есть яблоко.','an','["a", "an", "the"]','an — перед гласным звуком'),
('en','article','A1','articles',22,'She has ___ dog.','У неё есть собака.','a','["a", "an", "the"]','a — перед согласным звуком'),
('en','article','A1','articles',23,'___ sun is hot.','Солнце горячее.','The','["A", "An", "The"]','the — единственное в своём роде'),
('en','article','A1','articles',24,'He is ___ engineer.','Он инженер.','an','["a", "an", "the"]','an engineer — гласный звук'),
('en','article','A1','articles',25,'Can you open ___ window?','Можешь открыть окно?','the','["a", "an", "the"]','the — конкретный предмет'),
('en','article','A1','articles',26,'She is ___ hour late.','Она опоздала на час.','an','["a", "an", "the"]','an hour — h не читается'),
('en','article','A1','articles',27,'We live in ___ city.','Мы живём в городе.','a','["a", "an", "the"]','a — неопределённый'),
('en','article','A1','articles',28,'He has ___ umbrella.','У него есть зонт.','an','["a", "an", "the"]','an umbrella — гласный звук'),
('es','conjugation','A1','ser',1,'yo ___ estudiante','я студент','soy','["soy", "eres", "es"]','ser: soy, eres, es, somos, sois, son'),
('es','conjugation','A1','ser',2,'tú ___ profesor','ты преподаватель','eres','["soy", "eres", "es"]','ser: soy, eres, es, somos, sois, son'),
('es','conjugation','A1','ser',3,'él ___ alto','он высокий','es','["soy", "eres", "es"]','ser: soy, eres, es, somos, sois, son'),
('es','conjugation','A1','ser',4,'nosotros ___ amigos','мы друзья','somos','["somos", "sois", "son"]','ser: soy, eres, es, somos, sois, son'),
('es','conjugation','A1','ser',5,'ellos ___ españoles','они испанцы','son','["somos", "sois", "son"]','ser: soy, eres, es, somos, sois, son'),
('es','conjugation','A1','tener',6,'yo ___ un coche','у меня есть машина','tengo','["tengo", "tienes", "tiene"]','tener: tengo, tienes, tiene, tenemos, tenéis, tienen'),
('es','conjugation','A1','tener',7,'tú ___ hambre','ты голоден','tienes','["tengo", "tienes", "tiene"]','tener: tengo, tienes, tiene, tenemos, tenéis, tienen'),
('es','conjugation','A1','tener',8,'ella ___ tiempo','у неё есть время','tiene','["tengo", "tienes", "tiene"]','tener: tengo, tienes, tiene, tenemos, tenéis, tienen'),
('es','conjugation','A1','hablar',9,'yo ___ español','я говорю по-испански','hablo','["hablo", "hablas", "habla"]','-ar: -o, -as, -a, -amos, -áis, -an'),
('es','conjugation','A1','hablar',10,'tú ___ inglés','ты говоришь по-английски','hablas','["hablo", "hablas", "habla"]','-ar: -o, -as, -a, -amos, -áis, -an'),
('es','conjugation','A1','hablar',11,'nosotros ___ mucho','мы много говорим','hablamos','["hablamos", "habláis", "hablan"]','-ar: -o, -as, -a, -amos, -áis, -an'),
('es','article','A1','articulos',12,'___ casa','дом → ж.р.','la','["el", "la", "los"]','femenino: la'),
('es','article','A1','articulos',13,'___ libro','книга → м.р.','el','["el", "la", "las"]','masculino: el'),
('es','article','A1','articulos',14,'___ mesa','стол → ж.р.','la','["el", "la", "los"]','femenino: la'),
('es','article','A1','articulos',15,'___ perros','собаки (мн.)','los','["el", "los", "las"]','masculino plural: los'),
('es','article','A1','articulos',16,'___ flores','цветы (мн.)','las','["los", "las", "el"]','femenino plural: las'),
('es','article','A1','articulos',17,'___ coche','машина → м.р.','el','["el", "la", "los"]','masculino: el'),
('fr','conjugation','A1','etre',1,'je ___ étudiant','я студент','suis','["suis", "es", "est"]','être: suis, es, est, sommes, êtes, sont'),
('fr','conjugation','A1','etre',2,'tu ___ professeur','ты преподаватель','es','["suis", "es", "est"]','être: suis, es, est, sommes, êtes, sont'),
('fr','conjugation','A1','etre',3,'il ___ grand','он высокий','est','["suis", "es", "est"]','être: suis, es, est, sommes, êtes, sont'),
('fr','conjugation','A1','etre',4,'nous ___ amis','мы друзья','sommes','["sommes", "êtes", "sont"]','être: suis, es, est, sommes, êtes, sont'),
('fr','conjugation','A1','etre',5,'ils ___ français','они французы','sont','["sommes", "êtes", "sont"]','être: suis, es, est, sommes, êtes, sont'),
('fr','conjugation','A1','avoir',6,'j''___ une voiture','у меня есть машина','ai','["ai", "as", "a"]','avoir: ai, as, a, avons, avez, ont'),
('fr','conjugation','A1','avoir',7,'tu ___ faim','ты голоден','as','["ai", "as", "a"]','avoir: ai, as, a, avons, avez, ont'),
('fr','conjugation','A1','avoir',8,'elle ___ le temps','у неё есть время','a','["ai", "as", "a"]','avoir: ai, as, a, avons, avez, ont'),
('fr','conjugation','A1','parler',9,'je ___ français','я говорю по-французски','parle','["parle", "parles", "parlons"]','-er: -e, -es, -e, -ons, -ez, -ent'),
('fr','conjugation','A1','parler',10,'tu ___ anglais','ты говоришь по-английски','parles','["parle", "parles", "parlons"]','-er: -e, -es, -e, -ons, -ez, -ent'),
('fr','conjugation','A1','parler',11,'nous ___ beaucoup','мы много говорим','parlons','["parle", "parles", "parlons"]','-er: -e, -es, -e, -ons, -ez, -ent'),
('fr','article','A1','articles',12,'___ maison','дом → ж.р.','la','["le", "la", "les"]','féminin: la'),
('fr','article','A1','articles',13,'___ livre','книга → м.р.','le','["le", "la", "les"]','masculin: le'),
('fr','article','A1','articles',14,'___ table','стол → ж.р.','la','["le", "la", "les"]','féminin: la'),
('fr','article','A1','articles',15,'___ enfants','дети (мн.)','les','["le", "la", "les"]','pluriel: les'),
('fr','article','A1','articles',16,'___ voiture (неопр.)','машина → ж.р.','une','["un", "une", "des"]','féminin: une'),
('fr','article','A1','articles',17,'___ ami (неопр.)','друг → м.р.','un','["un", "une", "des"]','masculin: un'),
('de','conjugation','A1','sein',1,'ich ___ Student','я студент','bin','["bin", "bist", "ist"]','sein: bin, bist, ist, sind, seid, sind'),
('de','conjugation','A1','sein',2,'du ___ Lehrer','ты учитель','bist','["bin", "bist", "ist"]','sein: bin, bist, ist, sind, seid, sind'),
('de','conjugation','A1','sein',3,'er ___ groß','он высокий','ist','["bin", "bist", "ist"]','sein: bin, bist, ist, sind, seid, sind'),
('de','conjugation','A1','sein',4,'wir ___ Freunde','мы друзья','sind','["sind", "seid", "ist"]','sein: bin, bist, ist, sind, seid, sind'),
('de','conjugation','A1','sein',5,'sie ___ Deutsche','они немцы','sind','["sind", "seid", "bin"]','sein: bin, bist, ist, sind, seid, sind'),
('de','conjugation','A1','haben',6,'ich ___ ein Auto','у меня есть машина','habe','["habe", "hast", "hat"]','haben: habe, hast, hat, haben, habt, haben'),
('de','conjugation','A1','haben',7,'du ___ Hunger','ты голоден','hast','["habe", "hast", "hat"]','haben: habe, hast, hat, haben, habt, haben'),
('de','conjugation','A1','haben',8,'sie ___ Zeit','у неё есть время','hat','["habe", "hast", "hat"]','haben: habe, hast, hat, haben, habt, haben'),
('de','conjugation','A1','sprechen',9,'ich ___ Deutsch','я говорю по-немецки','spreche','["spreche", "sprichst", "spricht"]','sprechen (e→i): spreche, sprichst, spricht, sprechen, sprecht, sprechen'),
('de','conjugation','A1','sprechen',10,'du ___ Englisch','ты говоришь по-английски','sprichst','["spreche", "sprichst", "spricht"]','sprechen (e→i): spreche, sprichst, spricht, sprechen, sprecht, sprechen'),
('de','conjugation','A1','sprechen',11,'wir ___ viel','мы много говорим','sprechen','["spreche", "sprichst", "sprechen"]','sprechen (e→i): spreche, sprichst, spricht, sprechen, sprecht, sprechen'),
('de','article','A1','artikel',12,'___ Mann','мужчина → м.р.','der','["der", "die", "das"]','мужской род: der'),
('de','article','A1','artikel',13,'___ Frau','женщина → ж.р.','die','["der", "die", "das"]','женский род: die'),
('de','article','A1','artikel',14,'___ Kind','ребёнок → ср.р.','das','["der", "die", "das"]','средний род: das'),
('de','article','A1','artikel',15,'___ Haus','дом → ср.р.','das','["der", "die", "das"]','средний род: das'),
('de','article','A1','artikel',16,'___ Auto','машина → ср.р.','das','["der", "die", "das"]','средний род: das'),
('de','article','A1','artikel',17,'___ Tisch','стол → м.р.','der','["der", "die", "das"]','мужской род: der'),
('de','article','A1','artikel',18,'___ Katze','кошка → ж.р.','die','["der", "die", "das"]','женский род: die'),
('de','article','A1','artikel',19,'___ Buch','книга → ср.р.','das','["der", "die", "das"]','средний род: das');
